version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123@abcd
    ports:
      - "3306:3306"
    networks:
      - local

networks:
  local:
    driver: bridge
